export const enum Events {
    Connect = "connect",
    Disconnect = "disconnect",
    Connection = "connection",
    ChatMessage = "chat_message",
    Typing = "typing",
    StopTyping = "stop_typing",
    JoinRoom = "join_room",
    LeaveRoom = "leave_room",
    GetRooms = "get_rooms",
    RoomsList = "rooms_list",
    UserJoined = "user_joined",
    UserLeft = "user_left",
    GetUsers = "get_users",
    UsersList = "users_list",
    RoomCreated = "room_created",
    GetUserInfo = "get_user_info",
    UserInfo = "user_info",
    JoinedRoom = "joined_room",
    UserMention = "user_mention",
    AuthenticationSuccess = "authentication_success",
    AuthenticationFailed = "authentication_failed",
    UserLogin = "user_login"
}